// Generated by gencpp from file omni_shot/way_points.msg
// DO NOT EDIT!


#ifndef OMNI_SHOT_MESSAGE_WAY_POINTS_H
#define OMNI_SHOT_MESSAGE_WAY_POINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <omni_shot/way_point.h>

namespace omni_shot
{
template <class ContainerAllocator>
struct way_points_
{
  typedef way_points_<ContainerAllocator> Type;

  way_points_()
    : header()
    , path()
    , sample(0)  {
    }
  way_points_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , path(_alloc)
    , sample(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::omni_shot::way_point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::omni_shot::way_point_<ContainerAllocator> >::other >  _path_type;
  _path_type path;

   typedef uint8_t _sample_type;
  _sample_type sample;




  typedef boost::shared_ptr< ::omni_shot::way_points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_shot::way_points_<ContainerAllocator> const> ConstPtr;

}; // struct way_points_

typedef ::omni_shot::way_points_<std::allocator<void> > way_points;

typedef boost::shared_ptr< ::omni_shot::way_points > way_pointsPtr;
typedef boost::shared_ptr< ::omni_shot::way_points const> way_pointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omni_shot::way_points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omni_shot::way_points_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omni_shot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'omni_shot': ['/home/nathaniel/Documents/Omnibot/code/catkin_ws/src/omni_shot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omni_shot::way_points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_shot::way_points_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_shot::way_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_shot::way_points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_shot::way_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_shot::way_points_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omni_shot::way_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1847c8a7cc942338a5e4611b252b7e5a";
  }

  static const char* value(const ::omni_shot::way_points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1847c8a7cc942338ULL;
  static const uint64_t static_value2 = 0xa5e4611b252b7e5aULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_shot::way_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omni_shot/way_points";
  }

  static const char* value(const ::omni_shot::way_points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omni_shot::way_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
omni_shot/way_point[] path\n\
uint8 sample\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: omni_shot/way_point\n\
Header header\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Twist velocity\n\
float32 time\n\
\n\
	\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::omni_shot::way_points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omni_shot::way_points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.path);
      stream.next(m.sample);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct way_points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_shot::way_points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omni_shot::way_points_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::omni_shot::way_point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
    s << indent << "sample: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sample);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNI_SHOT_MESSAGE_WAY_POINTS_H
