set(_CATKIN_CURRENT_PACKAGE "omni_shot")
set(omni_shot_VERSION "0.0.0")
set(omni_shot_MAINTAINER "nathaniel <nathaniel@todo.todo>")
set(omni_shot_PACKAGE_FORMAT "1")
set(omni_shot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "nav_core" "message_generation")
set(omni_shot_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "nav_core" "message_runtime")
set(omni_shot_BUILDTOOL_DEPENDS "catkin")
set(omni_shot_BUILDTOOL_EXPORT_DEPENDS )
set(omni_shot_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "nav_core" "message_runtime")
set(omni_shot_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "nav_core" "message_runtime")
set(omni_shot_TEST_DEPENDS )
set(omni_shot_DOC_DEPENDS )
set(omni_shot_DEPRECATED "")